subprojects {
	group = 'com.sunyesle'
	version = '0.0.1-SNAPSHOT'

	repositories {
		mavenCentral()
	}

	plugins.withId('org.springframework.boot') {
		bootBuildImage {
			builder = 'paketobuildpacks/builder-jammy-tiny'
			imageName = "sunyesle/${project.name}"
			publish = true
			docker {
				publishRegistry {
					username = "${dockerUsername}"
					password = "${dockerPassword}"
				}
			}
		}
	}
}
