apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tempo
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        runAsNonRoot: true
      containers:
        - image: grafana/tempo:2.6.1
          name: tempo
          ports:
            - containerPort: 3200
              name: tempo
            - containerPort: 9411
              name: zipkin
          args: ["-config.file=/etc/tempo.yaml"]
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
            - name: tempo-data
              mountPath: /var/tempo
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
        - name: tempo-data
          persistentVolumeClaim:
            claimName: tempo-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tempo
  name: tempo
spec:
  ports:
    - port: 3200
      protocol: TCP
      targetPort: 3200
      name: tempo
    - port: 9411
      protocol: TCP
      targetPort: 9411
      name: zipkin
  selector:
    app: tempo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tempo-pv
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/tempo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        zipkin: {}

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/blocks
